import Link from "next/link";
/**
 * Section 08 — native details/summary, no JS needed to open them.
 *
 * Ported verbatim from the delivered homepage package
 * (website-and-ops/GoodGround-Homepage-Live-Files). Styling lives in
 * home2026.css, scoped so it cannot reach the rest of the site.
 */
export function Faq() {
  return (
    <section className="faq section-light section-pad" id="faq" aria-labelledby="faq-title"><div className="wrap faq-layout"><div className="faq-intro"><p className="eyebrow">08 / FAQ</p><h2 className="section-title reveal" id="faq-title">Everything<br />you need<br />to know<span className="accent-text">.</span></h2><Link className="text-link" href="/faq">Find all questions here <span aria-hidden="true">↗︎</span></Link></div><div className="faq-list">
          <details open><summary><span className="faq-number">01</span><h3>How do the two payment options work?</h3><span className="faq-symbol" aria-hidden="true"></span></summary><div className="faq-answer"><p>We agree on one fixed price for your project up front. No hourly billing and no scope surprises. From there, you choose how to pay it: a 50% deposit to secure the project and the remaining 50% on completion, before handover, or 12 equal monthly instalments, where the first instalment secures your booking and the remaining 11 become payable once the project is completed. Either way, you always know exactly what you’re paying and when.</p></div></details>
          <details><summary><span className="faq-number">02</span><h3>Is there a deposit before you start?</h3><span className="faq-symbol" aria-hidden="true"></span></summary><div className="faq-answer"><p>It depends which option you choose. With the deposit option, yes: 50% upfront secures the project, with the balance due on completion. With the 12-month plan, your first instalment secures the booking instead, a smaller amount than a full deposit, and the remaining 11 instalments only start once the project is completed.</p></div></details>
          <details><summary><span className="faq-number">03</span><h3>What happens if the project scope changes partway through?</h3><span className="faq-symbol" aria-hidden="true"></span></summary><div className="faq-answer"><p>We’ll always let you know before any change affects the price. If you add scope beyond what was originally agreed, we’ll quote that separately rather than silently adjusting what you’ve already agreed to pay.</p></div></details>
          <details><summary><span className="faq-number">04</span><h3>What if I need to pause or cancel partway through the project?</h3><span className="faq-symbol" aria-hidden="true"></span></summary><div className="faq-answer"><p>The project price is fixed, however you choose to pay it. If you cancel partway through, the outstanding balance of that agreed price becomes payable, whichever payment option you chose. The full cancellation terms are set out in our <a href="/legal#terms">Terms and Conditions</a> and written into the contract you sign before we start, so nothing about it catches you out later.</p></div></details>
          <details><summary><span className="faq-number">05</span><h3>Do you only build websites, or do you handle design and SEO too?</h3><span className="faq-symbol" aria-hidden="true"></span></summary><div className="faq-answer"><p>Every website we build includes the design, UX, and SEO foundations as part of one process, so you don’t need to brief a separate designer or SEO specialist. One team, one project, one price.</p></div></details>
          <details><summary><span className="faq-number">06</span><h3>How long does a typical project take?</h3><span className="faq-symbol" aria-hidden="true"></span></summary><div className="faq-answer"><p>Most website projects take about 4 to 6 weeks from start to launch. The exact time depends on the scope and what your project needs, and we’ll give you a firmer estimate once we’ve scoped it together.</p></div></details>
          <details><summary><span className="faq-number">07</span><h3>What happens after my website launches?</h3><span className="faq-symbol" aria-hidden="true"></span></summary><div className="faq-answer"><p>Launch is the start, not the finish line. If you’d rather have it all handled, our Full Service package bundles hosting, mailboxes, ongoing SEO work, and ongoing updates and maintenance into one monthly price.</p></div></details>
          <details><summary><span className="faq-number">08</span><h3>Do you work with businesses anywhere in South Africa?</h3><span className="faq-symbol" aria-hidden="true"></span></summary><div className="faq-answer"><p>Yes. We work with businesses right across South Africa. The whole process runs comfortably online, so where you’re based is never a barrier.</p></div></details>
        </div></div></section>
  );
}
